<a href="https://colab.research.google.com/github/pialXVII/Python/blob/CSE111-OOP/cse111_lab06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#task1
class Student:
  id=0
  def __init__(self,name,dept,age,cg):
    self.name=name
    self.dept=dept
    self.age=age
    self.cgpa=cg
    Student.id+=1
    self.id=Student.id

  def showDetails(self):
    print(f"""ID: {self.id}
Name: {self.name}
Department: {self.dept}
Age: {self.age}
CGPA: {self.cgpa}""")

  @classmethod
  def from_String(cls,s):
    x=s.split('-')
    obj=cls(x[0],x[1],x[2],x[3])
    return obj




s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [ ]:
#task2
class Assassin:
  total=0
  def __init__(self,name,rate):
    self.name=name
    self.rate=rate
    Assassin.total+=1

  def printDetails(self):
    print(f'''Name: {self.name}
Success rate: {self.rate}%
Total number of Assassin: {Assassin.total}''')

  @classmethod
  def failureRate(cls,name,fr):
    obj=cls(name,100-fr)
    return obj

  @classmethod
  def failurePercentage(cls,name,fp):
    fp=int(fp[:len(fp)-1])
    obj=cls(name,100-fp)
    return obj



john_wick = Assassin('John Wick', 100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage("Akabane", "10%")
akabane.printDetails()

Name: John Wick
Success rate: 100%
Total number of Assassin: 1
================================
Name: Nagisa
Success rate: 80%
Total number of Assassin: 2
================================
Name: Akabane
Success rate: 90%
Total number of Assassin: 3

In [ ]:
#task 3
class Passenger:
  count=0
  def __init__(self,name):
    self.name=name
    self.busFare=450
    Passenger.count+=1

  def set_bag_weight(self,w):
    if 21<=w<=50:
      self.busFare+=50
    elif w>50:
      self.busFare+=100

  def printDetail(self):
    print(f"Name: {self.name}")
    print(f"Bus Fare: {self.busFare}")

print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus Fare: 550
=========================
Name: Carol
Bus Fare: 450
=========================
Name: Mike
Bus Fare: 500
=========================
Total Passenger: 3

In [ ]:
#task4
class Travel:
  count=0
  def __init__(self,s,d):
    self.source=s
    self.destination=d
    self.time=1
    Travel.count+=1

  def display_travel_info(self):
    return(f"""Source: {self.source}
Destination:{self.destination}
Flight Time:{self.time}:00""")

  def set_time(self,t):
    self.time=t

  def set_source(self,s):
    self.source=s

  def set_destination(self,d):
    self.destination=d


print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =", Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination:India
Flight Time:1:00
=======================
Source: Kuala Lampur
Destination:Dhaka
Flight Time:23:00
=======================
Source: Dhaka
Destination:Germany
Flight Time:15:00
=======================
Source: Malaysia
Destination:Canada
Flight Time:9:00
=======================
No. of Traveller = 4

In [ ]:
#task5
class Employee:
  def __init__(self,name,period):
    self.name=name
    self.workingPeriod=period

  @classmethod
  def employeeByJoiningYear(cls,name,yr):
    obj=cls(name,2023-yr)
    return obj

  @staticmethod
  def experienceCheck(hour,gender):
    if hour<3:
      if gender== 'male':
        return f"He is not experienced"
      else:
        return f"She is not experienced"
    else:
      if gender== 'male':
        return f"He is experienced"
      else:
        return f"She is experienced"






employee1 = Employee('Dororo', 3)
employee2 = Employee.employeeByJoiningYear('Harry', 2016)
print(employee1.workingPeriod)
print(employee2.workingPeriod)
print(employee1.name)
print(employee2.name)
print(Employee.experienceCheck(2, "male"))
print(Employee.experienceCheck(3, "female"))

3
7
Dororo
Harry
He is not experienced
She is experienced

In [ ]:
#task6
class Laptop:
  laptopCount=0
  def __init__(self,name,count):
    self.name=name
    self.count=count
    Laptop.laptopCount+=count

  @staticmethod
  def advantage():
    print('Laptops are portable')

  @classmethod
  def resetCount(cls):
    cls.laptopCount=0



lenovo = Laptop("Lenovo", 5)
dell = Laptop("Dell", 7)
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

Lenovo 5
Dell 7
Total number of Laptops 12
Laptops are portable
Total number of Laptops 0

In [ ]:
#task7
class Cat:
  Number_of_cats = 0

  def __init__(self, colour, action):
    self.colour = colour
    self.action = action
    Cat.Number_of_cats += 1

  @classmethod
  def no_parameter(cls):
    return cls("White", "sitting")

  @classmethod
  def first_parameter(cls, colour):
    return cls(colour, "sitting")

  @classmethod
  def second_parameter(cls, action):
    return cls("Grey", action)

  def changeColor(self, colour):
    self.colour = colour

  def printCat(self):
    print(f"{self.colour} cat is {self.action}")

print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

Total number of cats: 0
=======================
White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Grey cat is playing
Blue cat is sitting
Purple cat is jumping
=======================
Total number of cats: 5

In [ ]:
#task8
import math
class Cylinder:
  height=18
  radius=5
  def __init__(self,r,h):
    self.height=h
    self.radius=r
    print(f"""Default radius={Cylinder.radius} and height={Cylinder.height}.
Updated: radius={self.radius} and height={self.height}.""")
    Cylinder.radius=self.radius
    Cylinder.height=self.height

  @staticmethod
  def area(r,h):
    a= (2*math.pi*r*r) + (2*math.pi*r*h)
    print(f"Area: {a}")

  @staticmethod
  def volume(r,h):
    v=math.pi*r*r*h
    print(f"Volume:  {v}")

  @classmethod
  def swap(cls,r,h):
    obj=cls(h,r)
    return obj

  @classmethod
  def changeFormat(cls,s):
    x=s.split('-')
    obj=cls(float(x[0]),float(x[1]))
    return obj






c1 = Cylinder(0,0)
Cylinder.area(c1.radius,c1.height)
Cylinder.volume(c1.radius,c1.height)
print("===============================")
c2 = Cylinder.swap(8,3)
c2.area(c2.radius,c2.height)
c2.volume(c2.radius,c2.height)
print("===============================")
c3 = Cylinder.changeFormat("7-13")
c3.area(c3.radius,c3.height)
c3.volume(c3.radius,c3.height)
print("===============================")
Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)
print("===============================")
Cylinder(3,5).volume(Cylinder.radius,Cylinder.height)

Default radius=5 and height=18.
Updated: radius=0 and height=0.
Area: 0.0
Volume:  0.0
===============================
Default radius=0 and height=0.
Updated: radius=3 and height=8.
Area: 207.34511513692635
Volume:  226.1946710584651
===============================
Default radius=3 and height=8.
Updated: radius=7.0 and height=13.0.
Area: 879.645943005142
Volume:  2001.1945203366981
===============================
Default radius=7.0 and height=13.0.
Updated: radius=0.3 and height=5.56.
Area: 11.045839770021713
===============================
Default radius=0.3 and height=5.56.
Updated: radius=3 and height=5.
Volume:  141.3716694115407

In [ ]:
#task9
class Student:
  total=0
  brac=0
  other=0
  def __init__(self,name,dept,ins='BRAC University'):
    self.name=name
    self.dept=dept
    self.institution=ins
    Student.total+=1
    if self.institution == 'BRAC University':
      Student.brac+=1
    else:
      Student.other+=1

  @classmethod
  def createStudent(cls,name,dept,ins='BRAC University'):
    obj = cls(name,dept,ins)
    return obj

  @classmethod
  def printDetails(cls):
    print(f"""Total Student(s): {cls.total}
BRAC University Student(s): {cls.brac}
Other Institution Student(s): {cls.other}""")

  def individualDetail(self):
    print(f"Name: {self.name}")
    print(f"Department: {self.dept}")
    print(f"Institution: {self.institution}")


Student.printDetails()
print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution: BRAC University
------------------------------------------
Total Student(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Student(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department: CSE
Institution: BRAC University
--------------------------------------------
Total Student(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1

In [ ]:

#task10
class SultansDine:
  totalBranch=0
  totalSell=0
  total=[]

  def __init__(self,name):
    self.name=name
    self.sell=0
    SultansDine.totalBranch+=1
    SultansDine.total.append(self.name)


  def sellQuantity(self,n):
    if n <10:

      SultansDine.totalSell+= 300*n
      self.sell= 300*n
      SultansDine.total.append(self.sell)
    elif n <20:

      SultansDine.totalSell+= 350*n
      self.sell= 350*n
      SultansDine.total.append(self.sell)
    else:


      SultansDine.totalSell+= 400*n
      self.sell = 400*n
      SultansDine.total.append(self.sell)


  def branchInformation(self):
    print(f"""Branch Name: {self.name}
Branch Sell: {self.sell} Taka""")

  @classmethod
  def details(cls):
    print(f"""Total Number of branch(s):{cls.totalBranch}
Total Sell: {cls.totalSell} Taka""")
    if len(cls.total)!=0:

      for i in range(0,len(cls.total)-1,2):
        print(f'Branch Name: {cls.total[i]}, Branch Sell: {cls.total[i+1]} Taka')
        percent=( cls.total[i+1] / cls.totalSell )*100
        print(f"Branch consists of total sell's: {percent:.2f}%")








SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s):0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 10000 Taka
-----------------------------------------
Total Number of branch(s):1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 100.00%
========================
Branch Name: Baily Road
Branch Sell: 5250 Taka
-----------------------------------------
Total Number of branch(s):2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 65.57%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700 Taka
-----------------------------------------
Total Number of branch(s):3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 55.71%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 29.25%
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch consists of total sell's: 15.04%

In [ ]:








SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s):0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 0 Taka
-----------------------------------------
Total Number of branch(s):1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 100.00%
========================
Branch Name: Baily Road
Branch Sell: 0 Taka
-----------------------------------------
Total Number of branch(s):2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 65.57%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 0 Taka
-----------------------------------------
Total Number of branch(s):3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 55.71%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 29.25%
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch consists of total sell's: 15.04%

In [ ]:
#task11
class Puzzle:
    x = 0
    def methodA(self):
        Puzzle.x = 5
        z = Puzzle.x + self.methodB(Puzzle.x)
        print(Puzzle.x, z)
        z = self.methodB(z + 2) + Puzzle.x
        print(Puzzle.x, z)
        self.methodB(Puzzle.x, z)
        print(Puzzle.x, z)
    def methodB(self, *args):
        if len(args) == 1:
            y = args[0]
            Puzzle.x = y + Puzzle.x
            print(Puzzle.x, y)
            return Puzzle.x + 3
        else:
            z, x = args
            z = z + 1
            x = x + 1
            print(z, x)

p = Puzzle()
p.methodA()
p.methodA()
p = Puzzle()
p.methodA()
p.methodB(7)

10 5
10 18
30 20
30 63
31 64
30 63
10 5
10 18
30 20
30 63
31 64
30 63
10 5
10 18
30 20
30 63
31 64
30 63
37 7

40